# Summary Notes from DATA602 Required Youtube Videos

## Core Python Concepts

In [1]:
#obligatory!!!
print( 'Hello World' )

Hello World


### Comments
Leave lots of comment with '#' in your code to document what you are doing

In [ ]:
# this is an example comment. it will not be evaluated by the python interpreter. it is here to halp hoomans

### Variables
a variable is like an empty bucket. The bucket has a label that identifies the bucket and holds a value. at any given time the variable can hold only one object(value)

In [3]:
# example variable
a = 5
print( a ) # tell the python interpreter to pass the value of the variable 'a' to the function 'print' to display

5


In [4]:
b = 11 # another variable
print( a + b ) # print evaluates what it is given and displays the result

16


In [5]:
# not just numbers, variables can be different 'types'
c = 'Hello DATA602' # a string
d = 35.02 # a float
e = True # a bool
#there are other types too, but you get the idea

In [6]:
# to get the type of the value a variable holds, use the type() function
print( type( a ) )
print( type( d ) )
print( type( c ) )

<class 'int'>
<class 'float'>
<class 'str'>


python is a **loosely typed language**. This means that a variable can be declared, but it's type is implied and may be changed on the fly. This is different from strongly typed languages where the type of a variable must be declared & adhered to (e.g. C & Go) 

In [7]:
var1 = 'I am a string' #initialize as a string
print( type( var1 ) )
var1 = 13  #recast as an int
print( type( var1 ) )

<class 'str'>
<class 'int'>


In [12]:
#standard operators for maths with int/float

#addition
x = 2 + a
#subtraction
y = x - 6
#multiplication
z = x * y
#division
v = 4 / 2
#exponent
u = z ** v
#floor division
t = 37 // 6
#modulo
s = 37 % 6

In [30]:
#in the right context, some operators can be used with strings.
s1 = 'ice'
s2 = 'cream'

#addition
s3 = s1 + s2
print( s3 )

#multiplication
print( s3 * 10 )

icecream
icecreamicecreamicecreamicecreamicecreamicecreamicecreamicecreamicecreamicecream


### Loops
allow us to iterate through code to repeat the execution of a block of code.

In [19]:
#example for loop
for n in [ 0,1,2,3,4 ]: #give 'n' the value of each successive iteration through the given range.
    print( "let's gooooo" ) #execute any indented line that occurs after the semicolon
print( "let's stop" ) #this line will not execute until after the for loop has iterated through    

let's gooooo
let's gooooo
let's gooooo
let's gooooo
let's gooooo
let's stop


In [18]:
#you can use the value 'n'
for n in range( 1,6 ):
    print( n, 'klondike bar' )

1 klondike bar
2 klondike bar
3 klondike bar
4 klondike bar
5 klondike bar


In [20]:
num = 0
for n in range( 1,1001 ): # range is great for lists of values that are too long to type
    num += n
print( num )    

500500


### Functions
a way to take a block of code & give it a label. the label can then be called in place of retyping all that code.

In [21]:
def my_first_function(): #anything indented after this semicolon will be defined as our new function
    print( 'hello' )
    print( 'how are you? ' )

In [22]:
#call the function so that it executes it's code
my_first_function()

hello
how are you? 


functions can act as a black box: you can put information in as arguments and return values back:

In [27]:
def how_many_klondikebars( num ): #the parentheses are a door for you to pass arguments to the function
    result = 'I would like ' + str( num ) + ' klondike bars. ' + str( num - 1 ) + ' is not enough.'
    return result

bars = how_many_klondikebars( 6 )
print( bars )

I would like 6 klondike bars. 5 is not enough.


In [31]:
def multiplier( x1, x2 ):
    res = x1 * x2
    return res

r1 = multiplier( 5,6 )
print( r1 )

r2 = multiplier( 100, 3 )
print( r2 )

30
300


### Conditions
add logic to blocks of code to determine what does and does not get executed and when.

In [33]:
#if/ifelse/else statements control the logic of what blocks of code get executed
hungry = 1
thirsty = 1
if hungry == 1 and thirsty == 1:
    print( 'you should totally break for lunch.')
else:
    print( 'you should keep writing code.')

you should totally break for lunch.


In [37]:
#the while conditional controls the logic of when blocks of code get executed
temp = 75
hot = True

while hot:
    print( "it's hot!" )
    temp -= 2
    if temp < 60:
        hot = False
        print( "it's not hot anymore")
print( "it's " + str( temp ) )        

it's hot!
it's hot!
it's hot!
it's hot!
it's hot!
it's hot!
it's hot!
it's hot!
it's not hot anymore
it's 59


### User Input
allow a user to enter values

In [38]:
user_input = input( 'pick a number' )

pick a number6


In [39]:
user_input

'6'

### Putting it all Together

In [40]:
def menu():
print( "1. Trade\n2. Show PnL\n3. Quit" )
    
done = False
while not done:
    menu()
    selected = input()
    if selected == "3":
        done = True
        
print( "thank you for trading with us.")        

1. Trade
2. Show PnL
3. Quit
1
1. Trade
2. Show PnL
3. Quit
1
1. Trade
2. Show PnL
3. Quit
2
1. Trade
2. Show PnL
3. Quit
1
1. Trade
2. Show PnL
3. Quit
3
thank you for trading with us.


## Python Native Data Structures

**What is a data structure?**  
a data structure gives a way to store and organize data that is more complex than primitives (float, int, bool, str).  
 
**Why aren't variables enough?"**  
1. it's a lot of work to explicitely define each piece of data in large data sets. and this approach makes it difficult to manipulate the data.
2. it's difficult to define new variables within complex control statements.
3. dealing with variables directly makes it difficults to make changes to data because the variable names would need to be hard-coded into script  

**Three main native Python data structures:**
1. Lists
2. Dictionaries
3. Tuples  

These 3 data structures are the basic structures that allow us to grapple with more complex data. There are more advanced structures such as pandas dataframes, but these form a basis set and are available on bare-bones Python installations.

### Lists
lists give access to a collectio of values. the values are grouped behind the same label, the list name. it is much easier to manipulate the values via the list name than it is to call each value by an unique name. Lists can be manipulated and modified as needed; that is to say, lists are mutable.

In [43]:
cars = ['Honda', 'Toyota', 'Mitsubishi', 'Tesla'] #lists are demarcated by square brackets '[]'
print( cars ) #creating a list give access to a set of values.

['Honda', 'Toyota', 'Mitsubishi', 'Tesla']


In [46]:
#select items in a list by index
print( cars[ 0:2 ] )
print( cars[ 2:4 ] )

['Honda', 'Toyota']
['Mitsubishi', 'Tesla']


In [47]:
cars.append( 'Lamborghini' ) #use the append method for lists
print( cars )

['Honda', 'Toyota', 'Mitsubishi', 'Tesla', 'Lamborghini']


In [49]:
print( cars[ :3 ] ) #assumes you mean start from 0
print( cars[ 2: ] ) #assumes you want to proceed through the end

['Honda', 'Toyota', 'Mitsubishi']
['Mitsubishi', 'Tesla', 'Lamborghini']


In [50]:
print( cars )
cars.append( 'Jeep' )
print( cars )
cars.append( 'Bugatti' )
print( cars )

['Honda', 'Toyota', 'Mitsubishi', 'Tesla', 'Lamborghini']
['Honda', 'Toyota', 'Mitsubishi', 'Tesla', 'Lamborghini', 'Jeep']
['Honda', 'Toyota', 'Mitsubishi', 'Tesla', 'Lamborghini', 'Jeep', 'Bugatti']


In [51]:
#can mutate items in a list
print( cars )
cars[2] = "Volkswagon"
print( cars )

['Honda', 'Toyota', 'Mitsubishi', 'Tesla', 'Lamborghini', 'Jeep', 'Bugatti']
['Honda', 'Toyota', 'Volkswagon', 'Tesla', 'Lamborghini', 'Jeep', 'Bugatti']


In [53]:
#can delete items from a list by index
print( cars )
del cars[ 0 ]
print( cars )

['Toyota', 'Volkswagon', 'Tesla', 'Lamborghini', 'Jeep', 'Bugatti']
['Volkswagon', 'Tesla', 'Lamborghini', 'Jeep', 'Bugatti']


In [54]:
#can delete items by valus from a list
cars.remove( 'Jeep' )
print( cars )

['Volkswagon', 'Tesla', 'Lamborghini', 'Bugatti']


In [55]:
#can clear a list entirely
print( cars )
cars.clear()
cars.append( 'Jeep' )
cars.append( 'Bugatti' )
print( cars )

['Volkswagon', 'Tesla', 'Lamborghini', 'Bugatti']
['Jeep', 'Bugatti']


In [56]:
#reversing the order of a list
cars.reverse()
print( cars )
cars.reverse()
print( cars )

['Bugatti', 'Jeep']
['Jeep', 'Bugatti']


In [62]:
#sort a list in ascending order
cars = ['Honda', 'Toyota', 'Mitsubishi', 'Tesla']
cars.sort()
print( cars )
#now descending order
cars.reverse()
print( cars )

['Honda', 'Mitsubishi', 'Tesla', 'Toyota']
['Toyota', 'Tesla', 'Mitsubishi', 'Honda']


In [63]:
#insert a value to a list at a specified index
print( cars )
cars.insert( 2, 'Lamborghini' )
cars.insert( 4, 'Ford' )
print( cars )

['Toyota', 'Tesla', 'Mitsubishi', 'Honda']
['Toyota', 'Tesla', 'Lamborghini', 'Mitsubishi', 'Ford', 'Honda']


In [64]:
#combine lists
print( cars )
more_cars = [ 'GM', 'Fiat' ]
cars.extend( more_cars )
print( cars )

['Toyota', 'Tesla', 'Lamborghini', 'Mitsubishi', 'Ford', 'Honda']
['Toyota', 'Tesla', 'Lamborghini', 'Mitsubishi', 'Ford', 'Honda', 'GM', 'Fiat']


helping methods to return information about a list object.

In [65]:
#find number of items in a list
print( len( cars ) )

8


In [68]:
num_list = [ 2,8,6,0,0,9,1,5,11,6,3,3,7,5,4,2,6 ]
#find the min or max in a list of values and other properties
print( max( num_list ) )
print( min( num_list ) )
print( sum( num_list ) )

11
0
78


In [69]:
#iterating through a list
for a in cars:
    print( a )

Toyota
Tesla
Lamborghini
Mitsubishi
Ford
Honda
GM
Fiat


In [70]:
#conditional across a list
if ('Fiat' in cars ):
    print( 'yes, there is a Fiat' )

yes, there is a Fiat


In [73]:
#two dimentional list
numbers = [ [1,2,3], [4,5,6], [7,8,9] ]
print( numbers )
print( numbers[0] )
print( numbers[0][2] )

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3]
3


In [74]:
#lists do not need to have the same data types
alist = [ 1, [2,3], 'four' ]
print( alist )

[1, [2, 3], 'four']


### Dictionaries
storing key:value pairs of data

In [76]:
#example dictionary
grades = { 'Sally':99, 'Greg':99, 'George':58 } #dictionaries use curly brackets
print( grades )

{'Sally': 99, 'Greg': 99, 'George': 58}


In [77]:
#access values by calls to keys
print( grades[ 'Greg' ] )

99


In [78]:
#can delete entries
del grades[ 'George' ]
print( grades )

{'Sally': 99, 'Greg': 99}


In [79]:
#can iterate through a dictionary
for k,v in grades.items():
    print( k,v )

Sally 99
Greg 99


### Tuples
tuples are similar to lists, however, big key difference, they are immutable. Once they are defined, they cannot be changed.  
**Why are tuples a thing**  
when a list is initialized, python allocates extra memory under the hood because it anticipates changes. However, if a collection of values is intended to be static, storing as a tuple allocates only what is needed. Tuples are a more memory efficient way of storing a static listing of values.

In [81]:
#initializing a tuple: use the curved brackets
cars = ( 'Hyundai', 'GM', 'Ford', 'Porsche' )
print( cars )

('Hyundai', 'GM', 'Ford', 'Porsche')


**cannot:** insert, delete, replace entries  
**can:** iterate over, index

In [82]:
#iteration
for c in cars:
    print( c )

Hyundai
GM
Ford
Porsche


In [83]:
#describe
print( len( cars ) )

4


For a more comprehensive summary of Python List, Dictionary and Tuple methods, visit [docs.python.org](https://docs.python.org/3/tutorial/datastructures.html)

## Overview of `NumPy`

### What is `NumPy`?

`NumPy` is a python library that has advances array management and functions for linear algebra, random numbers and Fourier transforms.  

See:
* [numpy.org](http://numpy.org)
* [numpy on git](https://github.com/numpy)

### What? Another data structure? Why do I need that?

Python native data structures are powerful, but:
* `NumPy` extends that power
* Python can be sow (Interpreted language), `NumPy` functions are written in C/C++, namely ndarray, therefore, `NumPy` offers speed with Python wrapper

### Demo - Using `NumPy`

In [1]:
#import numpy and give a shorter alias
import numpy as np 

#### Creating `np.array`s

In [26]:
a = np.ones( 5 )

def p_info( narray ):
    print( )
    print( narray )
    print( type( narray ) )
    print( narray.dtype )
    print( narray.shape )
    
p_info( a )    


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
float64
(5,)


In [7]:
a = np.zeros( 20 )
p_info( a )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
float64


In [8]:
a = np.eye( 4 )
p_info( a )

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>
float64


In [10]:
a = np.ones( (3, 10) )
p_info( a )

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
float64


**`np.linspace`**: returns evenly spaced numbers over a specified interval

In [12]:
#linspace
a = np.linspace( 2, 3, num=15 )
p_info( a )
a = np.linspace( 2, 3, num=5 )
p_info( a )

[2.         2.07142857 2.14285714 2.21428571 2.28571429 2.35714286
 2.42857143 2.5        2.57142857 2.64285714 2.71428571 2.78571429
 2.85714286 2.92857143 3.        ]
<class 'numpy.ndarray'>
float64
[2.   2.25 2.5  2.75 3.  ]
<class 'numpy.ndarray'>
float64


In [14]:
a = np.arange( 0,15 )
p_info( a )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
int64


In [15]:
alist = [ 1, 2, 3, 4, 5, 6 ]
a = np.array( alist )
p_info( a )

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int64


#### Referencing / Indexing

In [24]:
#Referencing/Indexing a np.array structure
a = np.arange( 50 )
p_info( a )

print( a[0:10] )
print( a[40::] )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
<class 'numpy.ndarray'>
int64
[0 1 2 3 4 5 6 7 8 9]
[40 41 42 43 44 45 46 47 48 49]


In [25]:
a = np.eye( 5 )
p_info( a )
print( a[3,2] )

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
float64
0.0


#### Reshaping

In [28]:
#Reshaping
a = np.arange( 20 )
p_info( a )
a = a.reshape( 4,5 ) #dimnesions have to fit
p_info( a )


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
int64
(20,)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
int64
(4, 5)


In [29]:
#combine them:
a = np.arange( 36 ).reshape( 6,6 )
p_info( a )


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
<class 'numpy.ndarray'>
int64
(6, 6)


#### Broadcasting

In [32]:
#Broadcasting
a = np.arange( 0,12 )
p_info( a )
b = a[0:3]
p_info( b )
#Broadcasting: any changes made to b manifest in a as well:
b[0] = 100
p_info( a )


[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
int64
(12,)

[0 1 2]
<class 'numpy.ndarray'>
int64
(3,)

[100   1   2   3   4   5   6   7   8   9  10  11]
<class 'numpy.ndarray'>
int64
(12,)


In [33]:
#avoiding broadcasting
c = a.copy()
c[0]= 1000
p_info( c )
p_info( a )


[1000    1    2    3    4    5    6    7    8    9   10   11]
<class 'numpy.ndarray'>
int64
(12,)

[100   1   2   3   4   5   6   7   8   9  10  11]
<class 'numpy.ndarray'>
int64
(12,)


#### Modifying arrays

In [46]:
#Modifying values
a = np.arange( 30 )
a[ 0 ] = 100
a[ 1:11 ] = 200
a = a.reshape( 3,10 )
a[1,1] = 3000
p_info( a )


[[ 100  200  200  200  200  200  200  200  200  200]
 [ 200 3000   12   13   14   15   16   17   18   19]
 [  20   21   22   23   24   25   26   27   28   29]]
<class 'numpy.ndarray'>
int64
(3, 10)


#### Built-in Calculations

In [49]:
#Built in Calculations
print( a.max() )
print( a.min() )
print( a.argmax() ) #index of max
print( a.argmin() ) #index of min

3000
12
11
12


`np.array` maths computes elementwise

In [52]:
print( a + a )
print( a - 1 )
print( a ** 2 )

[[ 200  400  400  400  400  400  400  400  400  400]
 [ 400 6000   24   26   28   30   32   34   36   38]
 [  40   42   44   46   48   50   52   54   56   58]]
[[  99  199  199  199  199  199  199  199  199  199]
 [ 199 2999   11   12   13   14   15   16   17   18]
 [  19   20   21   22   23   24   25   26   27   28]]
[[  10000   40000   40000   40000   40000   40000   40000   40000   40000
    40000]
 [  40000 9000000     144     169     196     225     256     289     324
      361]
 [    400     441     484     529     576     625     676     729     784
      841]]


#### Generating Random Numbers

In [58]:
#Random numbers
r = np.random.rand( 5 ) #return 5 random values that lie between 0 and 1 from a uniform distribution
p_info( r )
r2 = np.random.randn( 5 ) #return 5 random values from a standard normal distribution with mean=0 & var = 1
p_info( r2 )


[0.97981296 0.3703168  0.92492329 0.20417938 0.66549058]
<class 'numpy.ndarray'>
float64
(5,)

[-0.43517259  1.01897437  1.07217044 -1.04180214  0.89649975]
<class 'numpy.ndarray'>
float64
(5,)


In [ ]:
#2D arrays

#### Conditional Statements

In [62]:
#Conditional Selection from np.arrays
a = np.arange( 1,100 )
aidx = a > 50
b = a[ aidx == True ]
p_info( a )
p_info( aidx )
p_info( b )


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
<class 'numpy.ndarray'>
int64
(99,)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True]
<class 'numpy.ndarray'>
bool
(99,)

[51 52 53 54 55 56 

## Regression

### What is regression?

**Regression**: is a statistical method to determine the strnegth of the relationship of one variable to one or more other variables

### Intuition behind regression

**Linear Regression**: fitting a line to the data with equation:
$$y =mx + b$$
$$y = b_0 + b_1*x$$
where:
* x = independent variable   
* y = dependent variable (depends on the values to right of =)  
* m = slope (change in y)/(change in x)  
* b = y-intercept

#### Best fit
line that minimizes the residuals (difference between observed and predicted data)

### Ordinary Least Squares (OLS)
* Draw a line with random slope and offset
* Find the distance between each point and the line
* Square each distance
* Sum up all the squared distance
* Repeat until we've minimized the sum

### `scikit-learn` linear regression

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit( x,y )

### `R` linear regressiom
use the `lm()` function

### Why Linear Regression?
With a linear equation, we may be able to predict y for a future x provided the data behaves linearly.